// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdv13fyMng2i-VECYGE1VQ-wpEdezaXyc',
    appId: '1:234912838531:web:d54cb9092ec05b57c4fcb6',
    messagingSenderId: '234912838531',
    projectId: 'ecommerce-app-cc737',
    authDomain: 'ecommerce-app-cc737.firebaseapp.com',
    storageBucket: 'ecommerce-app-cc737.appspot.com',
    measurementId: 'G-39TM15D44K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3NZgF6HObEq425AwnYlPHjIr6FA3ZISQ',
    appId: '1:234912838531:android:c573876183c4a26fc4fcb6',
    messagingSenderId: '234912838531',
    projectId: 'ecommerce-app-cc737',
    storageBucket: 'ecommerce-app-cc737.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHlugVyGKQWHAok1btZ-NL1Ib2hBH4PjA',
    appId: '1:234912838531:ios:45a001d40dc4481fc4fcb6',
    messagingSenderId: '234912838531',
    projectId: 'ecommerce-app-cc737',
    storageBucket: 'ecommerce-app-cc737.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
